---
title: "Drake plan for Chapter 1"
drake_cache: ".dataCleaning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Makecondition

```{r makecondition}
library(dplyr)
library(tidyverse)
library(googlesheets4)
library(econDV)
library(lubridate)
# startSalary
# startSalary <- read_sheet(
#   "https://docs.google.com/spreadsheets/d/1PPWeFGqedVsgZmV81MeA0oJDCBkj5upkHltlWap7xUY/edit#gid=1835013852",
#   skip = 3
# )
# WDI::WDIsearch(string="Inflation") -> inflation_search
# inflation_search

# target_series <- inflation_search[1,]
world_inflation %=% WDI::WDI(
  indicator = "FP.CPI.TOTL.ZG" # target_series[["indicator"]]
)

df_cpiTW %=% {
  con <- url("https://www.dropbox.com/s/8585yr3t0bbcb5b/df_cpiTW.rda?dl=1")
  load(file = con)
  df_cpiTW
}

df_newTaipeiYouBike %=% jsonlite::fromJSON(
  "https://data.ntpc.gov.tw/api/datasets/71CD1490-A2DF-4198-BEF1-318479775E8A/json"
) # data.frame classlibrary(googlesheets4)
library(econDV)
# startSalary
startSalary %=% read_sheet(
  "https://docs.google.com/spreadsheets/d/1PPWeFGqedVsgZmV81MeA0oJDCBkj5upkHltlWap7xUY/edit#gid=1835013852",
  skip = 3
)
# WDI::WDIsearch(string="Inflation") -> inflation_search
# inflation_search

# target_series <- inflation_search[1,]
world_inflation %=% WDI::WDI(
  indicator = "FP.CPI.TOTL.ZG" # target_series[["indicator"]]
)

df_cpiTW %=% {
  con <- url("https://www.dropbox.com/s/8585yr3t0bbcb5b/df_cpiTW.rda?dl=1")
  load(file = con)
  df_cpiTW
}

df_newTaipeiYouBike %=% jsonlite::fromJSON(
  "https://data.ntpc.gov.tw/api/datasets/71CD1490-A2DF-4198-BEF1-318479775E8A/json"
) # data.frame class
```

```{r cpiTWopenData}
cpiTWopenData = {
  library(xml2)
  require(econDV)
  cpiTW <- read_xml("https://www.dgbas.gov.tw/public/data/open/Stat/price/PR0101A1M.xml") 
xml2::as_list(cpiTW) -> list_cpiTW
  list_cpiTW
}

```

styler

```{r}
{
require(purrr)
sublist <- list_cpiTW$DataSet
# .x 1:77112
(sublist[[1]]$Item == "總指數(民國105年=100)") & (
  sublist[[1]]$TYPE == "年增率(%)"
)
(sublist[[2]]$Item == "總指數(民國105年=100)") & (
  sublist[[2]]$TYPE == "年增率(%)"
)

(sublist[[77000]]$Item == "總指數(民國105年=100)") & (
  sublist[[77000]]$TYPE == "年增率(%)"
)

~ {
  (.x$Item == "總指數(民國105年=100)") & (
    .x$TYPE == "年增率(%)"
  )
}
sublist %>%
  map(
    ~ {
      (.x$Item == "總指數(民國105年=100)") & (
        .x$TYPE == "年增率(%)"
      )
    }
  ) -> pickTarget
  
  head(
    unlist(pickTarget),20)
  
  totalCPIList <- sublist[unlist(pickTarget)]
  View(totalCPIList)
  
}
```


```{r}

  ##
  totalCPIList[[1]]

  data.frame(
    Item=totalCPIList[[1]]$Item[[1]],
    TIME_PERIOD=totalCPIList[[1]]$TIME_PERIOD[[1]],
    inflationRate=totalCPIList[[1]]$Item_VALUE[[1]]
  ) 
  
  totalCPIList[[2]]

  data.frame(
    Item=totalCPIList[[2]]$Item[[1]],
    TIME_PERIOD=totalCPIList[[2]]$TIME_PERIOD[[1]],
    inflationRate=totalCPIList[[2]]$Item_VALUE[[1]]
  ) 
  
  totalCPIList %>%
    map_dfr(
  ~{data.frame(
    Item=.x$Item[[1]],
    TIME_PERIOD=.x$TIME_PERIOD[[1]],
    inflationRate=.x$Item_VALUE[[1]]
  ) }
      
    ) -> df_inflationTW
  
  View(df_inflationTW)
  
```


```{r}
a <- c(2, 5, 8)
a[c(T,F,T)]
alist <- 
  list(
    2,
    5,
    8
  )
alist[c(T,F,T)]
```



# youBikeRightClass
```{r youBikeRightClass}
youBikeRightClass = { # deal with class
  df_newTaipeiYouBike %>% map(class)
  
  numericVs <- c("tot","sbi","lat","lng")
  
  df_newTaipeiYouBike %>% 
    mutate(
      across(
        all_of(numericVs),
        as.numeric
      )
    ) -> df_newTaipeiYouBike2
  
  factorVs <- c("sarea")
  df_newTaipeiYouBike2 %>%
    mutate(
      across(
        all_of(factorVs),
        as.factor
      )
    ) -> df_newTaipeiYouBike3
  
  df_newTaipeiYouBike3 %>%
    mutate(
      mday=ymd_hms(mday)
    )
}
```

# checkNA
```{r checkNA}
checkNA={
  totNA <- function(.x) sum(is.na(.x))
  smplSize <- function(.x) length(.x) - totNA(.x)
  youBikeRightClass %>%
    summarise(
      across(
        everything(),
        list(na=totNA, size=smplSize) # na, size會成為欄位名稱一部份
      )
    )
}
```

# data cleaning
```{r df_inflationTW}
df_inflationTW={
  require(lubridate)
  df_cpiTW %>%
    filter(
      str_detect(TYPE, "年增率"),
      Item=="總指數(民國105年=100)"
    ) %>% #View() %>%
    mutate(
      date=ymd(
        glue::glue("{TIME_PERIOD}D01")),
      year=year(date)
    ) %>%
    group_by(
      year
    ) %>%
    mutate(
      n=n() # n() basically count nObs
    ) %>%
    filter(
      n==12
    ) %>%
    mutate(
      Item_VALUE=parse_number(Item_VALUE)
    ) %>%
    summarise( # !!! summarise 一定會ungroup
      inflation=mean(Item_VALUE)
    ) %>%
    mutate(
      iso2c="TW",
      country="Taiwan"
    ) -> df_inflationTW
  df_inflationTW
}
```
## ggplot trial

```{r}

```


```{r baseCanvas}
baseCanvas = {
  df_inflationTW %>%
  ggplot()
  }
```

```{r geom1}
geom1 = {
  baseCanvas+
  geom_line(
    aes(x=year, y=inflation)
  )
}
```




```{r geom2}
geom2 =  {
    baseCanvas+
      geom_line(
        aes(x=year, y=inflation),
        size=2
        
      )
  }

```


```{r}
df_inflationTW %>% names
```


# df_worldInflation
```{r df_worldInflation}
df_worldInflation={
  world_inflation %>%
    rename(
      inflation=FP.CPI.TOTL.ZG
    ) -> world_inflation2
  
  world_inflation2 %>%
    bind_rows(
      df_inflationTW
    ) -> df_worldInflation
  
  df_worldInflation
}
```

# world_inflationComplete
```{r world_inflationComplete}
world_inflationComplete = {
  world_inflation %>%
    rename(
      inflation=FP.CPI.TOTL.ZG
    ) -> world_inflation2
  
  bind_rows(
    df_inflationTW,
    world_inflation2
  )
}
```

# world_inflationWithTaiwan
```{r world_inflationWithTaiwan}
world_inflationWithTaiwan = {
  world_inflation %>%
    rename(
      inflation=FP.CPI.TOTL.ZG
    ) -> world_inflation2
  
  world_inflation2 %>%
    left_join(
      ISOcountry %>%
        select(-en), # 不選en
      by = c("iso2c" = "code")
    ) -> world_inflationWithTaiwan
  world_inflationWithTaiwan
}
```

# world_inflationComplete_wide
```{r world_inflationComplete_wide}
world_inflationComplete_wide = {
  world_inflationComplete %>%
    pivot_wider(
      id_cols = c("year", "country", "inflation"),
      names_from = "country",
      values_from = "inflation"
    ) ->
  world_inflationComplete_wide
  world_inflationComplete_wide
}
```

