---
title: "taiwanXMGDPRatio"
drake_cache: ".taiwanXMGDPRatio"
---

# makecondition

```{r makecondition}
library(stringr)
library(lubridate)
library(tidyr)
library(dplyr)
library(econDV)
library(WDI)
library(ggplot2)
rprojroot::is_rstudio_project -> .pj
.pj$make_fix_file() -> .root
```


## WDI search

```{r world_import}
world_import = {
  import_search <- WDIsearch(string = "Imports of goods and services")
  world_import %=% WDI(indicator = import_search[12, 1])
  world_import
}
```

```{r world_export}
world_export = {
  export_search <- WDIsearch(string = "Exports of goods and services")
  world_export %=% WDI(indicator = export_search[13, 1])
  world_export
}

```



## worldTrade

```{r worldTrade}
worldTrade = {
    worldTrade <- 
        world_import %>%
      inner_join(
        world_export %>% select(-country), 
        by = c("iso2c", "year")) %>%
      select(year, iso2c, country, contains("indicator")) %>%
      rename_with(
        .fn = function(x) {
          case_when(
              x == "indicator.x" ~ "M", 
              x == "indicator.y" ~"X", 
              TRUE ~ x)
        } #anonymouse function
      )
    worldTrade
}
```

## df_taiwanXMGDPratio

```{r df_taiwanXMGDPratio}
df_taiwanXMGDPratio = {
    load(url("https://www.dropbox.com/s/cjn53a4sroueyrz/df_taiwanGDPcomponents.rda?dl=1"))
    df_taiwanXMGDPratio <- df_taiwanGDPcomponents %>% mutate(year = year(time)) %>% 
        group_by(year) %>% mutate(n = n()) %>% ungroup() %>% 
        filter(n == 4) %>% group_by(year) %>% summarise(across(all_of(c("GDP", 
        "X", "M")), sum)) %>% mutate(across(all_of(c("X", "M")), 
        function(x) {
            round(x/.data$GDP * 100, 2)
        })) %>% select(year, X, M) %>% mutate(iso2c = "TW", country = "Tawain")
    df_taiwanXMGDPratio
}
```

## worldTradeIncTaiwan

```{r worldTradeIncTaiwan}
worldTradeIncTaiwan = {
    worldTradeIncTaiwan <- worldTrade %>% select(year, iso2c, 
        country, X, M) %>% bind_rows(df_taiwanXMGDPratio) %>% 
        left_join(econDV::ISOcountry, by = c(iso2c = "code")) %>% 
        na.omit() %>% group_by(year) %>% mutate(tradeVolume = X + 
        M, rank_tradeVolume = get_rankNumber(tradeVolume)) %>% 
        arrange(rank_tradeVolume) %>% ungroup()
    worldTradeIncTaiwan
}
```

## chosenYear

```{r chosenYear}
chosenYear = {
2017
}
```

## taiwan_layer

```{r taiwan_layer, drake=F}
taiwan_layer = {
    geom_point(data = df_taiwanXMGDPratio %>% filter(year == 
        chosenYear), aes(x = X, y = M), color = "#d54062", size = 2)
}
```

## canvasData

```{r canvasData}
canvasData = {
    worldTradeIncTaiwanchosenYear <- worldTradeIncTaiwan %>% 
        filter(year == chosenYear) %>% arrange(rank_tradeVolume) %>% 
        pivot_longer(cols = c("X", "M"), names_to = "type", values_to = "value")
    worldTradeIncTaiwanchosenYear %>% filter(rank_tradeVolume <= 
        40)
}
```

## gg_worldXMGDPRatio

```{r gg_worldXMGDPRatio}
gg_worldXMGDPRatio = {
    canvasData %>% ggplot() + geom_col(aes(x = zh, y = value, 
        fill = type)) + scale_x_discrete(limits = rev(canvasData$zh), 
        ) + scale_y_continuous(sec.axis = dup_axis()) + theme(axis.line.y = element_blank(), 
        panel.grid.major.x = element_line()) + coord_flip()
}
```

## save_gg_worldXMGDPRatio

```{r save_gg_worldXMGDPRatio}
save_gg_worldXMGDPRatio = {
    scale = 5/8
    height = 8
    ggsave(plot = gg_worldXMGDPRatio, filename = file.path(.root(), 
        "img", "gg_worldXMGDPRatio.svg"), height = height, width = scale * 
        height)
}
```

## openSVG

```{r openSVG, drake=T}
openSVG = {
    save_gg_worldXMGDPRatio
    svgOpen(file.path(.root(), "img", "gg_worldXMGDPRatio.svg"))
}
```

